### ISSUE TITLE
Add reboot option to win_join_domain module

### ISSUE THREAD

**Issue by christonog** [nlandais/ansible-modules-ctxs#1]
There should be an option to reboot a server once it has been joined/unjoined to a domain.

**Comment by nlandais** [comment]
This is a good idea, I would love to force the reboot as part of this module. But there is a caveat:  when a machine reboots, the WINRM connection is dropped, leading to a playbook run failure every single time. 
Rather than adding the reboot in this module, please use the win_reboot role available from the master branch immediately after running the join domain action.
